[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = "/work/standard-cognition"
to = "/work/standard-ai"
status = 301

[[redirects]]
from = "/craft"
to = "/"
status = 301

[[redirects]]
from = "/work"
to = "/"
status = 301
